/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jblas_util_ArchFlavor */

#ifndef _Included_org_jblas_util_ArchFlavor
#define _Included_org_jblas_util_ArchFlavor
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jblas_util_ArchFlavor_SSE
#define org_jblas_util_ArchFlavor_SSE 1L
#undef org_jblas_util_ArchFlavor_SSE2
#define org_jblas_util_ArchFlavor_SSE2 2L
#undef org_jblas_util_ArchFlavor_SSE3
#define org_jblas_util_ArchFlavor_SSE3 3L
#undef org_jblas_util_ArchFlavor_NO_SSE
#define org_jblas_util_ArchFlavor_NO_SSE -1L
/*
 * Class:     org_jblas_util_ArchFlavor
 * Method:    SSELevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jblas_util_ArchFlavor_SSELevel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
