/*
 * Wrapper files for LAPACK
 *
 * 
 * automatically generated by fortranwrapper
 * hacked together by Mikio L. Braun on December 29, 2006
 */

#include "blas_wrapper.h"
#include <stdio.h>
#include <stdlib.h>

 
extern void caxpy(int N, lw_complex_t* CA, lw_complex_t* CX, int INCX, lw_complex_t* CY, int INCY)
{
  extern void caxpy_(FINT N, FCOMPLEX CA, FCOMPLEX CX, FINT INCX, FCOMPLEX CY, FINT INCY);
  caxpy_(&N, CA, CX, &INCX, CY, &INCY);
}

extern void ccopy(int N, lw_complex_t* CX, int INCX, lw_complex_t* CY, int INCY)
{
  extern void ccopy_(FINT N, FCOMPLEX CX, FINT INCX, FCOMPLEX CY, FINT INCY);
  ccopy_(&N, CX, &INCX, CY, &INCY);
}

extern void cdotc(lw_complex_t* RETVAL, int N, lw_complex_t* CX, int INCX, lw_complex_t* CY, int INCY)
{
  extern void cdotc_(FCOMPLEX RETVAL, FINT N, FCOMPLEX CX, FINT INCX, FCOMPLEX CY, FINT INCY);
  cdotc_(RETVAL, &N, CX, &INCX, CY, &INCY);
}

extern void cdotu(lw_complex_t* RETVAL, int N, lw_complex_t* CX, int INCX, lw_complex_t* CY, int INCY)
{
  extern void cdotu_(FCOMPLEX RETVAL, FINT N, FCOMPLEX CX, FINT INCX, FCOMPLEX CY, FINT INCY);
  cdotu_(RETVAL, &N, CX, &INCX, CY, &INCY);
}

extern void cgbmv(char TRANS, int M, int N, int KL, int KU, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX, lw_complex_t* BETA, lw_complex_t* Y, int INCY)
{
  extern void cgbmv_(FCHAR TRANS, FINT M, FINT N, FINT KL, FINT KU, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX, FCOMPLEX BETA, FCOMPLEX Y, FINT INCY);
  cgbmv_(&TRANS, &M, &N, &KL, &KU, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void cgemm(char TRANSA, char TRANSB, int M, int N, int K, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB, lw_complex_t* BETA, lw_complex_t* C, int LDC)
{
  extern void cgemm_(FCHAR TRANSA, FCHAR TRANSB, FINT M, FINT N, FINT K, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB, FCOMPLEX BETA, FCOMPLEX C, FINT LDC);
  cgemm_(&TRANSA, &TRANSB, &M, &N, &K, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void cgemv(char TRANS, int M, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX, lw_complex_t* BETA, lw_complex_t* Y, int INCY)
{
  extern void cgemv_(FCHAR TRANS, FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX, FCOMPLEX BETA, FCOMPLEX Y, FINT INCY);
  cgemv_(&TRANS, &M, &N, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void cgerc(int M, int N, lw_complex_t* ALPHA, lw_complex_t* X, int INCX, lw_complex_t* Y, int INCY, lw_complex_t* A, int LDA)
{
  extern void cgerc_(FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX Y, FINT INCY, FCOMPLEX A, FINT LDA);
  cgerc_(&M, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void cgeru(int M, int N, lw_complex_t* ALPHA, lw_complex_t* X, int INCX, lw_complex_t* Y, int INCY, lw_complex_t* A, int LDA)
{
  extern void cgeru_(FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX Y, FINT INCY, FCOMPLEX A, FINT LDA);
  cgeru_(&M, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void chbmv(char UPLO, int N, int K, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX, lw_complex_t* BETA, lw_complex_t* Y, int INCY)
{
  extern void chbmv_(FCHAR UPLO, FINT N, FINT K, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX, FCOMPLEX BETA, FCOMPLEX Y, FINT INCY);
  chbmv_(&UPLO, &N, &K, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void chemm(char SIDE, char UPLO, int M, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB, lw_complex_t* BETA, lw_complex_t* C, int LDC)
{
  extern void chemm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB, FCOMPLEX BETA, FCOMPLEX C, FINT LDC);
  chemm_(&SIDE, &UPLO, &M, &N, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void chemv(char UPLO, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX, lw_complex_t* BETA, lw_complex_t* Y, int INCY)
{
  extern void chemv_(FCHAR UPLO, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX, FCOMPLEX BETA, FCOMPLEX Y, FINT INCY);
  chemv_(&UPLO, &N, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void cher(char UPLO, int N, float ALPHA, lw_complex_t* X, int INCX, lw_complex_t* A, int LDA)
{
  extern void cher_(FCHAR UPLO, FINT N, FREAL ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX A, FINT LDA);
  cher_(&UPLO, &N, &ALPHA, X, &INCX, A, &LDA);
}

extern void cher2(char UPLO, int N, lw_complex_t* ALPHA, lw_complex_t* X, int INCX, lw_complex_t* Y, int INCY, lw_complex_t* A, int LDA)
{
  extern void cher2_(FCHAR UPLO, FINT N, FCOMPLEX ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX Y, FINT INCY, FCOMPLEX A, FINT LDA);
  cher2_(&UPLO, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void cher2k(char UPLO, char TRANS, int N, int K, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB, float BETA, lw_complex_t* C, int LDC)
{
  extern void cher2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB, FREAL BETA, FCOMPLEX C, FINT LDC);
  cher2k_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void cherk(char UPLO, char TRANS, int N, int K, float ALPHA, lw_complex_t* A, int LDA, float BETA, lw_complex_t* C, int LDC)
{
  extern void cherk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FREAL ALPHA, FCOMPLEX A, FINT LDA, FREAL BETA, FCOMPLEX C, FINT LDC);
  cherk_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, &BETA, C, &LDC);
}

extern void chpmv(char UPLO, int N, lw_complex_t* ALPHA, lw_complex_t* AP, lw_complex_t* X, int INCX, lw_complex_t* BETA, lw_complex_t* Y, int INCY)
{
  extern void chpmv_(FCHAR UPLO, FINT N, FCOMPLEX ALPHA, FCOMPLEX AP, FCOMPLEX X, FINT INCX, FCOMPLEX BETA, FCOMPLEX Y, FINT INCY);
  chpmv_(&UPLO, &N, ALPHA, AP, X, &INCX, BETA, Y, &INCY);
}

extern void chpr(char UPLO, int N, float ALPHA, lw_complex_t* X, int INCX, lw_complex_t* AP)
{
  extern void chpr_(FCHAR UPLO, FINT N, FREAL ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX AP);
  chpr_(&UPLO, &N, &ALPHA, X, &INCX, AP);
}

extern void chpr2(char UPLO, int N, lw_complex_t* ALPHA, lw_complex_t* X, int INCX, lw_complex_t* Y, int INCY, lw_complex_t* AP)
{
  extern void chpr2_(FCHAR UPLO, FINT N, FCOMPLEX ALPHA, FCOMPLEX X, FINT INCX, FCOMPLEX Y, FINT INCY, FCOMPLEX AP);
  chpr2_(&UPLO, &N, ALPHA, X, &INCX, Y, &INCY, AP);
}

extern void crotg(lw_complex_t* CA, lw_complex_t* CB, float C, lw_complex_t* S)
{
  extern void crotg_(FCOMPLEX CA, FCOMPLEX CB, FREAL C, FCOMPLEX S);
  crotg_(CA, CB, &C, S);
}

extern void cscal(int N, lw_complex_t* CA, lw_complex_t* CX, int INCX)
{
  extern void cscal_(FINT N, FCOMPLEX CA, FCOMPLEX CX, FINT INCX);
  cscal_(&N, CA, CX, &INCX);
}

extern void csscal(int N, float SA, lw_complex_t* CX, int INCX)
{
  extern void csscal_(FINT N, FREAL SA, FCOMPLEX CX, FINT INCX);
  csscal_(&N, &SA, CX, &INCX);
}

extern void cswap(int N, lw_complex_t* CX, int INCX, lw_complex_t* CY, int INCY)
{
  extern void cswap_(FINT N, FCOMPLEX CX, FINT INCX, FCOMPLEX CY, FINT INCY);
  cswap_(&N, CX, &INCX, CY, &INCY);
}

extern void csymm(char SIDE, char UPLO, int M, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB, lw_complex_t* BETA, lw_complex_t* C, int LDC)
{
  extern void csymm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB, FCOMPLEX BETA, FCOMPLEX C, FINT LDC);
  csymm_(&SIDE, &UPLO, &M, &N, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void csyr2k(char UPLO, char TRANS, int N, int K, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB, lw_complex_t* BETA, lw_complex_t* C, int LDC)
{
  extern void csyr2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB, FCOMPLEX BETA, FCOMPLEX C, FINT LDC);
  csyr2k_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void csyrk(char UPLO, char TRANS, int N, int K, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* BETA, lw_complex_t* C, int LDC)
{
  extern void csyrk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX BETA, FCOMPLEX C, FINT LDC);
  csyrk_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, BETA, C, &LDC);
}

extern void ctbmv(char UPLO, char TRANS, char DIAG, int N, int K, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX)
{
  extern void ctbmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX);
  ctbmv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void ctbsv(char UPLO, char TRANS, char DIAG, int N, int K, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX)
{
  extern void ctbsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX);
  ctbsv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void ctpmv(char UPLO, char TRANS, char DIAG, int N, lw_complex_t* AP, lw_complex_t* X, int INCX)
{
  extern void ctpmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FCOMPLEX AP, FCOMPLEX X, FINT INCX);
  ctpmv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void ctpsv(char UPLO, char TRANS, char DIAG, int N, lw_complex_t* AP, lw_complex_t* X, int INCX)
{
  extern void ctpsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FCOMPLEX AP, FCOMPLEX X, FINT INCX);
  ctpsv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void ctrmm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB)
{
  extern void ctrmm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB);
  ctrmm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, ALPHA, A, &LDA, B, &LDB);
}

extern void ctrmv(char UPLO, char TRANS, char DIAG, int N, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX)
{
  extern void ctrmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX);
  ctrmv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern void ctrsm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, lw_complex_t* ALPHA, lw_complex_t* A, int LDA, lw_complex_t* B, int LDB)
{
  extern void ctrsm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FCOMPLEX ALPHA, FCOMPLEX A, FINT LDA, FCOMPLEX B, FINT LDB);
  ctrsm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, ALPHA, A, &LDA, B, &LDB);
}

extern void ctrsv(char UPLO, char TRANS, char DIAG, int N, lw_complex_t* A, int LDA, lw_complex_t* X, int INCX)
{
  extern void ctrsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FCOMPLEX A, FINT LDA, FCOMPLEX X, FINT INCX);
  ctrsv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern double dasum(int N, double* DX, int INCX)
{
  extern double dasum_(FINT N, FDOUBLE DX, FINT INCX);
  return dasum_(&N, DX, &INCX);
}

extern void daxpy(int N, double DA, double* DX, int INCX, double* DY, int INCY)
{
  extern void daxpy_(FINT N, FDOUBLE DA, FDOUBLE DX, FINT INCX, FDOUBLE DY, FINT INCY);
  daxpy_(&N, &DA, DX, &INCX, DY, &INCY);
}

extern double dcabs1(lw_double_complex_t* Z)
{
  extern double dcabs1_(FDOUBLECOMPLEX Z);
  return dcabs1_(Z);
}

extern void dcopy(int N, double* DX, int INCX, double* DY, int INCY)
{
  extern void dcopy_(FINT N, FDOUBLE DX, FINT INCX, FDOUBLE DY, FINT INCY);
  dcopy_(&N, DX, &INCX, DY, &INCY);
}

extern double ddot(int N, double* DX, int INCX, double* DY, int INCY)
{
  extern double ddot_(FINT N, FDOUBLE DX, FINT INCX, FDOUBLE DY, FINT INCY);
  return ddot_(&N, DX, &INCX, DY, &INCY);
}

extern void dgbmv(char TRANS, int M, int N, int KL, int KU, double ALPHA, double* A, int LDA, double* X, int INCX, double BETA, double* Y, int INCY)
{
  extern void dgbmv_(FCHAR TRANS, FINT M, FINT N, FINT KL, FINT KU, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX, FDOUBLE BETA, FDOUBLE Y, FINT INCY);
  dgbmv_(&TRANS, &M, &N, &KL, &KU, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void dgemm(char TRANSA, char TRANSB, int M, int N, int K, double ALPHA, double* A, int LDA, double* B, int LDB, double BETA, double* C, int LDC)
{
  extern void dgemm_(FCHAR TRANSA, FCHAR TRANSB, FINT M, FINT N, FINT K, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE B, FINT LDB, FDOUBLE BETA, FDOUBLE C, FINT LDC);
  dgemm_(&TRANSA, &TRANSB, &M, &N, &K, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void dgemv(char TRANS, int M, int N, double ALPHA, double* A, int LDA, double* X, int INCX, double BETA, double* Y, int INCY)
{
  extern void dgemv_(FCHAR TRANS, FINT M, FINT N, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX, FDOUBLE BETA, FDOUBLE Y, FINT INCY);
  dgemv_(&TRANS, &M, &N, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void dger(int M, int N, double ALPHA, double* X, int INCX, double* Y, int INCY, double* A, int LDA)
{
  extern void dger_(FINT M, FINT N, FDOUBLE ALPHA, FDOUBLE X, FINT INCX, FDOUBLE Y, FINT INCY, FDOUBLE A, FINT LDA);
  dger_(&M, &N, &ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern double dnrm2(int N, double* X, int INCX)
{
  extern double dnrm2_(FINT N, FDOUBLE X, FINT INCX);
  return dnrm2_(&N, X, &INCX);
}

extern void drot(int N, double* DX, int INCX, double* DY, int INCY, double C, double S)
{
  extern void drot_(FINT N, FDOUBLE DX, FINT INCX, FDOUBLE DY, FINT INCY, FDOUBLE C, FDOUBLE S);
  drot_(&N, DX, &INCX, DY, &INCY, &C, &S);
}

extern void drotg(double DA, double DB, double C, double S)
{
  extern void drotg_(FDOUBLE DA, FDOUBLE DB, FDOUBLE C, FDOUBLE S);
  drotg_(&DA, &DB, &C, &S);
}

extern void dsbmv(char UPLO, int N, int K, double ALPHA, double* A, int LDA, double* X, int INCX, double BETA, double* Y, int INCY)
{
  extern void dsbmv_(FCHAR UPLO, FINT N, FINT K, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX, FDOUBLE BETA, FDOUBLE Y, FINT INCY);
  dsbmv_(&UPLO, &N, &K, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void dscal(int N, double DA, double* DX, int INCX)
{
  extern void dscal_(FINT N, FDOUBLE DA, FDOUBLE DX, FINT INCX);
  dscal_(&N, &DA, DX, &INCX);
}

extern void dspmv(char UPLO, int N, double ALPHA, double* AP, double* X, int INCX, double BETA, double* Y, int INCY)
{
  extern void dspmv_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE AP, FDOUBLE X, FINT INCX, FDOUBLE BETA, FDOUBLE Y, FINT INCY);
  dspmv_(&UPLO, &N, &ALPHA, AP, X, &INCX, &BETA, Y, &INCY);
}

extern void dspr(char UPLO, int N, double ALPHA, double* X, int INCX, double* AP)
{
  extern void dspr_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE X, FINT INCX, FDOUBLE AP);
  dspr_(&UPLO, &N, &ALPHA, X, &INCX, AP);
}

extern void dspr2(char UPLO, int N, double ALPHA, double* X, int INCX, double* Y, int INCY, double* AP)
{
  extern void dspr2_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE X, FINT INCX, FDOUBLE Y, FINT INCY, FDOUBLE AP);
  dspr2_(&UPLO, &N, &ALPHA, X, &INCX, Y, &INCY, AP);
}

extern void dswap(int N, double* DX, int INCX, double* DY, int INCY)
{
  extern void dswap_(FINT N, FDOUBLE DX, FINT INCX, FDOUBLE DY, FINT INCY);
  dswap_(&N, DX, &INCX, DY, &INCY);
}

extern void dsymm(char SIDE, char UPLO, int M, int N, double ALPHA, double* A, int LDA, double* B, int LDB, double BETA, double* C, int LDC)
{
  extern void dsymm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE B, FINT LDB, FDOUBLE BETA, FDOUBLE C, FINT LDC);
  dsymm_(&SIDE, &UPLO, &M, &N, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void dsymv(char UPLO, int N, double ALPHA, double* A, int LDA, double* X, int INCX, double BETA, double* Y, int INCY)
{
  extern void dsymv_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX, FDOUBLE BETA, FDOUBLE Y, FINT INCY);
  dsymv_(&UPLO, &N, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void dsyr(char UPLO, int N, double ALPHA, double* X, int INCX, double* A, int LDA)
{
  extern void dsyr_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE X, FINT INCX, FDOUBLE A, FINT LDA);
  dsyr_(&UPLO, &N, &ALPHA, X, &INCX, A, &LDA);
}

extern void dsyr2(char UPLO, int N, double ALPHA, double* X, int INCX, double* Y, int INCY, double* A, int LDA)
{
  extern void dsyr2_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLE X, FINT INCX, FDOUBLE Y, FINT INCY, FDOUBLE A, FINT LDA);
  dsyr2_(&UPLO, &N, &ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void dsyr2k(char UPLO, char TRANS, int N, int K, double ALPHA, double* A, int LDA, double* B, int LDB, double BETA, double* C, int LDC)
{
  extern void dsyr2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE B, FINT LDB, FDOUBLE BETA, FDOUBLE C, FINT LDC);
  dsyr2k_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void dsyrk(char UPLO, char TRANS, int N, int K, double ALPHA, double* A, int LDA, double BETA, double* C, int LDC)
{
  extern void dsyrk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE BETA, FDOUBLE C, FINT LDC);
  dsyrk_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, &BETA, C, &LDC);
}

extern void dtbmv(char UPLO, char TRANS, char DIAG, int N, int K, double* A, int LDA, double* X, int INCX)
{
  extern void dtbmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX);
  dtbmv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void dtbsv(char UPLO, char TRANS, char DIAG, int N, int K, double* A, int LDA, double* X, int INCX)
{
  extern void dtbsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX);
  dtbsv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void dtpmv(char UPLO, char TRANS, char DIAG, int N, double* AP, double* X, int INCX)
{
  extern void dtpmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLE AP, FDOUBLE X, FINT INCX);
  dtpmv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void dtpsv(char UPLO, char TRANS, char DIAG, int N, double* AP, double* X, int INCX)
{
  extern void dtpsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLE AP, FDOUBLE X, FINT INCX);
  dtpsv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void dtrmm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, double ALPHA, double* A, int LDA, double* B, int LDB)
{
  extern void dtrmm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE B, FINT LDB);
  dtrmm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, &ALPHA, A, &LDA, B, &LDB);
}

extern void dtrmv(char UPLO, char TRANS, char DIAG, int N, double* A, int LDA, double* X, int INCX)
{
  extern void dtrmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX);
  dtrmv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern void dtrsm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, double ALPHA, double* A, int LDA, double* B, int LDB)
{
  extern void dtrsm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FDOUBLE ALPHA, FDOUBLE A, FINT LDA, FDOUBLE B, FINT LDB);
  dtrsm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, &ALPHA, A, &LDA, B, &LDB);
}

extern void dtrsv(char UPLO, char TRANS, char DIAG, int N, double* A, int LDA, double* X, int INCX)
{
  extern void dtrsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLE A, FINT LDA, FDOUBLE X, FINT INCX);
  dtrsv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern double dzasum(int N, lw_double_complex_t* ZX, int INCX)
{
  extern double dzasum_(FINT N, FDOUBLECOMPLEX ZX, FINT INCX);
  return dzasum_(&N, ZX, &INCX);
}

extern double dznrm2(int N, lw_double_complex_t* X, int INCX)
{
  extern double dznrm2_(FINT N, FDOUBLECOMPLEX X, FINT INCX);
  return dznrm2_(&N, X, &INCX);
}

extern int icamax(int N, lw_complex_t* CX, int INCX)
{
  extern int icamax_(FINT N, FCOMPLEX CX, FINT INCX);
  return icamax_(&N, CX, &INCX);
}

extern int idamax(int N, double* DX, int INCX)
{
  extern int idamax_(FINT N, FDOUBLE DX, FINT INCX);
  return idamax_(&N, DX, &INCX);
}

extern int isamax(int N, float* SX, int INCX)
{
  extern int isamax_(FINT N, FREAL SX, FINT INCX);
  return isamax_(&N, SX, &INCX);
}

extern int izamax(int N, lw_double_complex_t* ZX, int INCX)
{
  extern int izamax_(FINT N, FDOUBLECOMPLEX ZX, FINT INCX);
  return izamax_(&N, ZX, &INCX);
}

extern lw_logical_t lsame(char CA, char CB)
{
  extern lw_logical_t lsame_(FCHAR CA, FCHAR CB);
  return lsame_(&CA, &CB);
}

extern float sasum(int N, float* SX, int INCX)
{
  extern float sasum_(FINT N, FREAL SX, FINT INCX);
  return sasum_(&N, SX, &INCX);
}

extern void saxpy(int N, float SA, float* SX, int INCX, float* SY, int INCY)
{
  extern void saxpy_(FINT N, FREAL SA, FREAL SX, FINT INCX, FREAL SY, FINT INCY);
  saxpy_(&N, &SA, SX, &INCX, SY, &INCY);
}


extern float scasum(int N, lw_complex_t* CX, int INCX)
{
  extern float scasum_(FINT N, FCOMPLEX CX, FINT INCX);
  return scasum_(&N, CX, &INCX);
}

extern float scnrm2(int N, lw_complex_t* X, int INCX)
{
  extern float scnrm2_(FINT N, FCOMPLEX X, FINT INCX);
  return scnrm2_(&N, X, &INCX);
}

extern void scopy(int N, float* SX, int INCX, float* SY, int INCY)
{
  extern void scopy_(FINT N, FREAL SX, FINT INCX, FREAL SY, FINT INCY);
  scopy_(&N, SX, &INCX, SY, &INCY);
}

extern float sdot(int N, float* SX, int INCX, float* SY, int INCY)
{
  extern float sdot_(FINT N, FREAL SX, FINT INCX, FREAL SY, FINT INCY);
  return sdot_(&N, SX, &INCX, SY, &INCY);
}

extern void sgbmv(char TRANS, int M, int N, int KL, int KU, float ALPHA, float* A, int LDA, float* X, int INCX, float BETA, float* Y, int INCY)
{
  extern void sgbmv_(FCHAR TRANS, FINT M, FINT N, FINT KL, FINT KU, FREAL ALPHA, FREAL A, FINT LDA, FREAL X, FINT INCX, FREAL BETA, FREAL Y, FINT INCY);
  sgbmv_(&TRANS, &M, &N, &KL, &KU, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void sgemm(char TRANSA, char TRANSB, int M, int N, int K, float ALPHA, float* A, int LDA, float* B, int LDB, float BETA, float* C, int LDC)
{
  extern void sgemm_(FCHAR TRANSA, FCHAR TRANSB, FINT M, FINT N, FINT K, FREAL ALPHA, FREAL A, FINT LDA, FREAL B, FINT LDB, FREAL BETA, FREAL C, FINT LDC);
  sgemm_(&TRANSA, &TRANSB, &M, &N, &K, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void sgemv(char TRANS, int M, int N, float ALPHA, float* A, int LDA, float* X, int INCX, float BETA, float* Y, int INCY)
{
  extern void sgemv_(FCHAR TRANS, FINT M, FINT N, FREAL ALPHA, FREAL A, FINT LDA, FREAL X, FINT INCX, FREAL BETA, FREAL Y, FINT INCY);
  sgemv_(&TRANS, &M, &N, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void sger(int M, int N, float ALPHA, float* X, int INCX, float* Y, int INCY, float* A, int LDA)
{
  extern void sger_(FINT M, FINT N, FREAL ALPHA, FREAL X, FINT INCX, FREAL Y, FINT INCY, FREAL A, FINT LDA);
  sger_(&M, &N, &ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern float snrm2(int N, float* X, int INCX)
{
  extern float snrm2_(FINT N, FREAL X, FINT INCX);
  return snrm2_(&N, X, &INCX);
}

extern void srot(int N, float* SX, int INCX, float* SY, int INCY, float C, float S)
{
  extern void srot_(FINT N, FREAL SX, FINT INCX, FREAL SY, FINT INCY, FREAL C, FREAL S);
  srot_(&N, SX, &INCX, SY, &INCY, &C, &S);
}

extern void srotg(float SA, float SB, float C, float S)
{
  extern void srotg_(FREAL SA, FREAL SB, FREAL C, FREAL S);
  srotg_(&SA, &SB, &C, &S);
}

extern void ssbmv(char UPLO, int N, int K, float ALPHA, float* A, int LDA, float* X, int INCX, float BETA, float* Y, int INCY)
{
  extern void ssbmv_(FCHAR UPLO, FINT N, FINT K, FREAL ALPHA, FREAL A, FINT LDA, FREAL X, FINT INCX, FREAL BETA, FREAL Y, FINT INCY);
  ssbmv_(&UPLO, &N, &K, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void sscal(int N, float SA, float* SX, int INCX)
{
  extern void sscal_(FINT N, FREAL SA, FREAL SX, FINT INCX);
  sscal_(&N, &SA, SX, &INCX);
}

extern void sspmv(char UPLO, int N, float ALPHA, float* AP, float* X, int INCX, float BETA, float* Y, int INCY)
{
  extern void sspmv_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL AP, FREAL X, FINT INCX, FREAL BETA, FREAL Y, FINT INCY);
  sspmv_(&UPLO, &N, &ALPHA, AP, X, &INCX, &BETA, Y, &INCY);
}

extern void sspr(char UPLO, int N, float ALPHA, float* X, int INCX, float* AP)
{
  extern void sspr_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL X, FINT INCX, FREAL AP);
  sspr_(&UPLO, &N, &ALPHA, X, &INCX, AP);
}

extern void sspr2(char UPLO, int N, float ALPHA, float* X, int INCX, float* Y, int INCY, float* AP)
{
  extern void sspr2_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL X, FINT INCX, FREAL Y, FINT INCY, FREAL AP);
  sspr2_(&UPLO, &N, &ALPHA, X, &INCX, Y, &INCY, AP);
}

extern void sswap(int N, float* SX, int INCX, float* SY, int INCY)
{
  extern void sswap_(FINT N, FREAL SX, FINT INCX, FREAL SY, FINT INCY);
  sswap_(&N, SX, &INCX, SY, &INCY);
}

extern void ssymm(char SIDE, char UPLO, int M, int N, float ALPHA, float* A, int LDA, float* B, int LDB, float BETA, float* C, int LDC)
{
  extern void ssymm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FREAL ALPHA, FREAL A, FINT LDA, FREAL B, FINT LDB, FREAL BETA, FREAL C, FINT LDC);
  ssymm_(&SIDE, &UPLO, &M, &N, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void ssymv(char UPLO, int N, float ALPHA, float* A, int LDA, float* X, int INCX, float BETA, float* Y, int INCY)
{
  extern void ssymv_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL A, FINT LDA, FREAL X, FINT INCX, FREAL BETA, FREAL Y, FINT INCY);
  ssymv_(&UPLO, &N, &ALPHA, A, &LDA, X, &INCX, &BETA, Y, &INCY);
}

extern void ssyr(char UPLO, int N, float ALPHA, float* X, int INCX, float* A, int LDA)
{
  extern void ssyr_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL X, FINT INCX, FREAL A, FINT LDA);
  ssyr_(&UPLO, &N, &ALPHA, X, &INCX, A, &LDA);
}

extern void ssyr2(char UPLO, int N, float ALPHA, float* X, int INCX, float* Y, int INCY, float* A, int LDA)
{
  extern void ssyr2_(FCHAR UPLO, FINT N, FREAL ALPHA, FREAL X, FINT INCX, FREAL Y, FINT INCY, FREAL A, FINT LDA);
  ssyr2_(&UPLO, &N, &ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void ssyr2k(char UPLO, char TRANS, int N, int K, float ALPHA, float* A, int LDA, float* B, int LDB, float BETA, float* C, int LDC)
{
  extern void ssyr2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FREAL ALPHA, FREAL A, FINT LDA, FREAL B, FINT LDB, FREAL BETA, FREAL C, FINT LDC);
  ssyr2k_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void ssyrk(char UPLO, char TRANS, int N, int K, float ALPHA, float* A, int LDA, float BETA, float* C, int LDC)
{
  extern void ssyrk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FREAL ALPHA, FREAL A, FINT LDA, FREAL BETA, FREAL C, FINT LDC);
  ssyrk_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, &BETA, C, &LDC);
}

extern void stbmv(char UPLO, char TRANS, char DIAG, int N, int K, float* A, int LDA, float* X, int INCX)
{
  extern void stbmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FREAL A, FINT LDA, FREAL X, FINT INCX);
  stbmv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void stbsv(char UPLO, char TRANS, char DIAG, int N, int K, float* A, int LDA, float* X, int INCX)
{
  extern void stbsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FREAL A, FINT LDA, FREAL X, FINT INCX);
  stbsv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void stpmv(char UPLO, char TRANS, char DIAG, int N, float* AP, float* X, int INCX)
{
  extern void stpmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FREAL AP, FREAL X, FINT INCX);
  stpmv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void stpsv(char UPLO, char TRANS, char DIAG, int N, float* AP, float* X, int INCX)
{
  extern void stpsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FREAL AP, FREAL X, FINT INCX);
  stpsv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void strmm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, float ALPHA, float* A, int LDA, float* B, int LDB)
{
  extern void strmm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FREAL ALPHA, FREAL A, FINT LDA, FREAL B, FINT LDB);
  strmm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, &ALPHA, A, &LDA, B, &LDB);
}

extern void strmv(char UPLO, char TRANS, char DIAG, int N, float* A, int LDA, float* X, int INCX)
{
  extern void strmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FREAL A, FINT LDA, FREAL X, FINT INCX);
  strmv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern void strsm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, float ALPHA, float* A, int LDA, float* B, int LDB)
{
  extern void strsm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FREAL ALPHA, FREAL A, FINT LDA, FREAL B, FINT LDB);
  strsm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, &ALPHA, A, &LDA, B, &LDB);
}

extern void strsv(char UPLO, char TRANS, char DIAG, int N, float* A, int LDA, float* X, int INCX)
{
  extern void strsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FREAL A, FINT LDA, FREAL X, FINT INCX);
  strsv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern int xerbla(int SRNAME)
{
  extern int xerbla_(FINT SRNAME, FINT INFO);
  int INFO;
  xerbla_(&SRNAME, &INFO);
  return INFO;
}

extern void zaxpy(int N, lw_double_complex_t* ZA, lw_double_complex_t* ZX, int INCX, lw_double_complex_t* ZY, int INCY)
{
  extern void zaxpy_(FINT N, FDOUBLECOMPLEX ZA, FDOUBLECOMPLEX ZX, FINT INCX, FDOUBLECOMPLEX ZY, FINT INCY);
  zaxpy_(&N, ZA, ZX, &INCX, ZY, &INCY);
}

extern void zcopy(int N, lw_double_complex_t* ZX, int INCX, lw_double_complex_t* ZY, int INCY)
{
  extern void zcopy_(FINT N, FDOUBLECOMPLEX ZX, FINT INCX, FDOUBLECOMPLEX ZY, FINT INCY);
  zcopy_(&N, ZX, &INCX, ZY, &INCY);
}

extern void zdotc(lw_double_complex_t* RETVAL, int N, lw_double_complex_t* ZX, int INCX, lw_double_complex_t* ZY, int INCY)
{
  extern void zdotc_(FDOUBLECOMPLEX RETVAL, FINT N, FDOUBLECOMPLEX ZX, FINT INCX, FDOUBLECOMPLEX ZY, FINT INCY);
  zdotc_(RETVAL, &N, ZX, &INCX, ZY, &INCY);
}

extern void zdotu(lw_double_complex_t* RETVAL, int N, lw_double_complex_t* ZX, int INCX, lw_double_complex_t* ZY, int INCY)
{
  extern void zdotu_(FDOUBLECOMPLEX RETVAL, FINT N, FDOUBLECOMPLEX ZX, FINT INCX, FDOUBLECOMPLEX ZY, FINT INCY);
  zdotu_(RETVAL, &N, ZX, &INCX, ZY, &INCY);
}

extern void zdscal(int N, double DA, lw_double_complex_t* ZX, int INCX)
{
  extern void zdscal_(FINT N, FDOUBLE DA, FDOUBLECOMPLEX ZX, FINT INCX);
  zdscal_(&N, &DA, ZX, &INCX);
}

extern void zgbmv(char TRANS, int M, int N, int KL, int KU, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX, lw_double_complex_t* BETA, lw_double_complex_t* Y, int INCY)
{
  extern void zgbmv_(FCHAR TRANS, FINT M, FINT N, FINT KL, FINT KU, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX Y, FINT INCY);
  zgbmv_(&TRANS, &M, &N, &KL, &KU, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void zgemm(char TRANSA, char TRANSB, int M, int N, int K, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB, lw_double_complex_t* BETA, lw_double_complex_t* C, int LDC)
{
  extern void zgemm_(FCHAR TRANSA, FCHAR TRANSB, FINT M, FINT N, FINT K, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX C, FINT LDC);
  zgemm_(&TRANSA, &TRANSB, &M, &N, &K, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void zgemv(char TRANS, int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX, lw_double_complex_t* BETA, lw_double_complex_t* Y, int INCY)
{
  extern void zgemv_(FCHAR TRANS, FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX Y, FINT INCY);
  zgemv_(&TRANS, &M, &N, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void zgerc(int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* Y, int INCY, lw_double_complex_t* A, int LDA)
{
  extern void zgerc_(FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX Y, FINT INCY, FDOUBLECOMPLEX A, FINT LDA);
  zgerc_(&M, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void zgeru(int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* Y, int INCY, lw_double_complex_t* A, int LDA)
{
  extern void zgeru_(FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX Y, FINT INCY, FDOUBLECOMPLEX A, FINT LDA);
  zgeru_(&M, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void zhbmv(char UPLO, int N, int K, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX, lw_double_complex_t* BETA, lw_double_complex_t* Y, int INCY)
{
  extern void zhbmv_(FCHAR UPLO, FINT N, FINT K, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX Y, FINT INCY);
  zhbmv_(&UPLO, &N, &K, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void zhemm(char SIDE, char UPLO, int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB, lw_double_complex_t* BETA, lw_double_complex_t* C, int LDC)
{
  extern void zhemm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX C, FINT LDC);
  zhemm_(&SIDE, &UPLO, &M, &N, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void zhemv(char UPLO, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX, lw_double_complex_t* BETA, lw_double_complex_t* Y, int INCY)
{
  extern void zhemv_(FCHAR UPLO, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX Y, FINT INCY);
  zhemv_(&UPLO, &N, ALPHA, A, &LDA, X, &INCX, BETA, Y, &INCY);
}

extern void zher(char UPLO, int N, double ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* A, int LDA)
{
  extern void zher_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX A, FINT LDA);
  zher_(&UPLO, &N, &ALPHA, X, &INCX, A, &LDA);
}

extern void zher2(char UPLO, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* Y, int INCY, lw_double_complex_t* A, int LDA)
{
  extern void zher2_(FCHAR UPLO, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX Y, FINT INCY, FDOUBLECOMPLEX A, FINT LDA);
  zher2_(&UPLO, &N, ALPHA, X, &INCX, Y, &INCY, A, &LDA);
}

extern void zher2k(char UPLO, char TRANS, int N, int K, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB, double BETA, lw_double_complex_t* C, int LDC)
{
  extern void zher2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB, FDOUBLE BETA, FDOUBLECOMPLEX C, FINT LDC);
  zher2k_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, B, &LDB, &BETA, C, &LDC);
}

extern void zherk(char UPLO, char TRANS, int N, int K, double ALPHA, lw_double_complex_t* A, int LDA, double BETA, lw_double_complex_t* C, int LDC)
{
  extern void zherk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLE ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLE BETA, FDOUBLECOMPLEX C, FINT LDC);
  zherk_(&UPLO, &TRANS, &N, &K, &ALPHA, A, &LDA, &BETA, C, &LDC);
}

extern void zhpmv(char UPLO, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* AP, lw_double_complex_t* X, int INCX, lw_double_complex_t* BETA, lw_double_complex_t* Y, int INCY)
{
  extern void zhpmv_(FCHAR UPLO, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX AP, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX Y, FINT INCY);
  zhpmv_(&UPLO, &N, ALPHA, AP, X, &INCX, BETA, Y, &INCY);
}

extern void zhpr(char UPLO, int N, double ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* AP)
{
  extern void zhpr_(FCHAR UPLO, FINT N, FDOUBLE ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX AP);
  zhpr_(&UPLO, &N, &ALPHA, X, &INCX, AP);
}

extern void zhpr2(char UPLO, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* X, int INCX, lw_double_complex_t* Y, int INCY, lw_double_complex_t* AP)
{
  extern void zhpr2_(FCHAR UPLO, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX X, FINT INCX, FDOUBLECOMPLEX Y, FINT INCY, FDOUBLECOMPLEX AP);
  zhpr2_(&UPLO, &N, ALPHA, X, &INCX, Y, &INCY, AP);
}

extern void zrotg(lw_double_complex_t* CA, lw_double_complex_t* CB, double C, lw_double_complex_t* S)
{
  extern void zrotg_(FDOUBLECOMPLEX CA, FDOUBLECOMPLEX CB, FDOUBLE C, FDOUBLECOMPLEX S);
  zrotg_(CA, CB, &C, S);
}

extern void zscal(int N, lw_double_complex_t* ZA, lw_double_complex_t* ZX, int INCX)
{
  extern void zscal_(FINT N, FDOUBLECOMPLEX ZA, FDOUBLECOMPLEX ZX, FINT INCX);
  zscal_(&N, ZA, ZX, &INCX);
}

extern void zswap(int N, lw_double_complex_t* ZX, int INCX, lw_double_complex_t* ZY, int INCY)
{
  extern void zswap_(FINT N, FDOUBLECOMPLEX ZX, FINT INCX, FDOUBLECOMPLEX ZY, FINT INCY);
  zswap_(&N, ZX, &INCX, ZY, &INCY);
}

extern void zsymm(char SIDE, char UPLO, int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB, lw_double_complex_t* BETA, lw_double_complex_t* C, int LDC)
{
  extern void zsymm_(FCHAR SIDE, FCHAR UPLO, FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX C, FINT LDC);
  zsymm_(&SIDE, &UPLO, &M, &N, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void zsyr2k(char UPLO, char TRANS, int N, int K, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB, lw_double_complex_t* BETA, lw_double_complex_t* C, int LDC)
{
  extern void zsyr2k_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX C, FINT LDC);
  zsyr2k_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, B, &LDB, BETA, C, &LDC);
}

extern void zsyrk(char UPLO, char TRANS, int N, int K, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* BETA, lw_double_complex_t* C, int LDC)
{
  extern void zsyrk_(FCHAR UPLO, FCHAR TRANS, FINT N, FINT K, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX BETA, FDOUBLECOMPLEX C, FINT LDC);
  zsyrk_(&UPLO, &TRANS, &N, &K, ALPHA, A, &LDA, BETA, C, &LDC);
}

extern void ztbmv(char UPLO, char TRANS, char DIAG, int N, int K, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX)
{
  extern void ztbmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX);
  ztbmv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void ztbsv(char UPLO, char TRANS, char DIAG, int N, int K, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX)
{
  extern void ztbsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FINT K, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX);
  ztbsv_(&UPLO, &TRANS, &DIAG, &N, &K, A, &LDA, X, &INCX);
}

extern void ztpmv(char UPLO, char TRANS, char DIAG, int N, lw_double_complex_t* AP, lw_double_complex_t* X, int INCX)
{
  extern void ztpmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLECOMPLEX AP, FDOUBLECOMPLEX X, FINT INCX);
  ztpmv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void ztpsv(char UPLO, char TRANS, char DIAG, int N, lw_double_complex_t* AP, lw_double_complex_t* X, int INCX)
{
  extern void ztpsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLECOMPLEX AP, FDOUBLECOMPLEX X, FINT INCX);
  ztpsv_(&UPLO, &TRANS, &DIAG, &N, AP, X, &INCX);
}

extern void ztrmm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB)
{
  extern void ztrmm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB);
  ztrmm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, ALPHA, A, &LDA, B, &LDB);
}

extern void ztrmv(char UPLO, char TRANS, char DIAG, int N, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX)
{
  extern void ztrmv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX);
  ztrmv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}

extern void ztrsm(char SIDE, char UPLO, char TRANSA, char DIAG, int M, int N, lw_double_complex_t* ALPHA, lw_double_complex_t* A, int LDA, lw_double_complex_t* B, int LDB)
{
  extern void ztrsm_(FCHAR SIDE, FCHAR UPLO, FCHAR TRANSA, FCHAR DIAG, FINT M, FINT N, FDOUBLECOMPLEX ALPHA, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX B, FINT LDB);
  ztrsm_(&SIDE, &UPLO, &TRANSA, &DIAG, &M, &N, ALPHA, A, &LDA, B, &LDB);
}

extern void ztrsv(char UPLO, char TRANS, char DIAG, int N, lw_double_complex_t* A, int LDA, lw_double_complex_t* X, int INCX)
{
  extern void ztrsv_(FCHAR UPLO, FCHAR TRANS, FCHAR DIAG, FINT N, FDOUBLECOMPLEX A, FINT LDA, FDOUBLECOMPLEX X, FINT INCX);
  ztrsv_(&UPLO, &TRANS, &DIAG, &N, A, &LDA, X, &INCX);
}
