/*
 * Wrapper files for FORTRAN
 *
 * automatically generated by fortranwrapper
 */

#ifndef <%= filename.upcase %>_H
#define <%= filename.upcase %>_H

typedef struct { float r; float i; } <%= C::COMPLEX_TYPE %>;
typedef struct { double r; double i; } <%= C::DOUBLE_COMPLEX_TYPE %>;

<% routines.each do |r| -%>
extern <%= C.declaration_for r %>;
<% end -%>

#endif
