/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhg_la_Blas */

#ifndef _Included_com_fhg_la_Blas
#define _Included_com_fhg_la_Blas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhg_la_Blas
 * Method:    caxpy
 * Signature: (ILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_caxpy
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ccopy
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ccopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cdotc
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)Lcom/fhg/core/FloatComplex;
 */
JNIEXPORT jobject JNICALL Java_com_fhg_la_Blas_cdotc
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cdotu
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)Lcom/fhg/core/FloatComplex;
 */
JNIEXPORT jobject JNICALL Java_com_fhg_la_Blas_cdotu
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cgbmv
 * Signature: (CIIIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cgbmv
  (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cgemm
 * Signature: (CCIIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cgemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cgemv
 * Signature: (CIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cgemv
  (JNIEnv *, jclass, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cgerc
 * Signature: (IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cgerc
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cgeru
 * Signature: (IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cgeru
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chbmv
 * Signature: (CIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chbmv
  (JNIEnv *, jclass, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chemm
 * Signature: (CCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chemv
 * Signature: (CILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chemv
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cher2
 * Signature: (CILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cher2
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cher2k
 * Signature: (CCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cher2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cher
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cher
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cherk
 * Signature: (CCIIFLjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cherk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chpmv
 * Signature: (CILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;ILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chpmv
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chpr2
 * Signature: (CILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chpr2
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    chpr
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_chpr
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    crotg
 * Signature: (Lcom/fhg/core/FloatComplex;Lcom/fhg/core/FloatComplex;FLcom/fhg/core/FloatComplex;)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_crotg
  (JNIEnv *, jclass, jobject, jobject, jfloat, jobject);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cscal
 * Signature: (ILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cscal
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    csscal
 * Signature: (IFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_csscal
  (JNIEnv *, jclass, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    cswap
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_cswap
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    csymm
 * Signature: (CCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_csymm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    csyr2k
 * Signature: (CCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_csyr2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    csyrk
 * Signature: (CCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_csyrk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctbmv
 * Signature: (CCCIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctbmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctbsv
 * Signature: (CCCIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctbsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctpmv
 * Signature: (CCCILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctpmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctpsv
 * Signature: (CCCILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctpsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctrmm
 * Signature: (CCCCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctrmm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctrmv
 * Signature: (CCCILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctrmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctrsm
 * Signature: (CCCCIILcom/fhg/core/FloatComplex;Ljava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctrsm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ctrsv
 * Signature: (CCCILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ctrsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dasum
 * Signature: (ILjava/nio/DoubleBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_dasum
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    daxpy
 * Signature: (IDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_daxpy
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dcabs1
 * Signature: (Lcom/fhg/core/DoubleComplex;)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_dcabs1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dcopy
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dcopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ddot
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_ddot
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dgbmv
 * Signature: (CIIIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dgbmv
  (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dgemm
 * Signature: (CCIIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dgemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dgemv
 * Signature: (CIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dgemv
  (JNIEnv *, jclass, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dger
 * Signature: (IIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dger
  (JNIEnv *, jclass, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dnrm2
 * Signature: (ILjava/nio/DoubleBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_dnrm2
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    drot
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDD)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_drot
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     com_fhg_la_Blas
 * Method:    drotg
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_drotg
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsbmv
 * Signature: (CIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsbmv
  (JNIEnv *, jclass, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dscal
 * Signature: (IDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dscal
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dspmv
 * Signature: (CIDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dspmv
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dspr2
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dspr2
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dspr
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dspr
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dswap
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dswap
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsymm
 * Signature: (CCIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsymm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsymv
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsymv
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsyr2
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsyr2
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsyr2k
 * Signature: (CCIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsyr2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsyr
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsyr
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dsyrk
 * Signature: (CCIIDLjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dsyrk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtbmv
 * Signature: (CCCIILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtbmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtbsv
 * Signature: (CCCIILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtbsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtpmv
 * Signature: (CCCILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtpmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtpsv
 * Signature: (CCCILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtpsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtrmm
 * Signature: (CCCCIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtrmm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtrmv
 * Signature: (CCCILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtrmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtrsm
 * Signature: (CCCCIIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtrsm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dtrsv
 * Signature: (CCCILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_dtrsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dzasum
 * Signature: (ILjava/nio/DoubleBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_dzasum
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    dznrm2
 * Signature: (ILjava/nio/DoubleBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_Blas_dznrm2
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    icamax
 * Signature: (ILjava/nio/FloatBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_Blas_icamax
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    idamax
 * Signature: (ILjava/nio/DoubleBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_Blas_idamax
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    isamax
 * Signature: (ILjava/nio/FloatBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_Blas_isamax
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    izamax
 * Signature: (ILjava/nio/DoubleBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_Blas_izamax
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    lsame
 * Signature: (CC)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_Blas_lsame
  (JNIEnv *, jclass, jchar, jchar);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sasum
 * Signature: (ILjava/nio/FloatBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_sasum
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    saxpy
 * Signature: (IFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_saxpy
  (JNIEnv *, jclass, jint, jfloat, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    scabs1
 * Signature: (Lcom/fhg/core/FloatComplex;)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_scabs1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_fhg_la_Blas
 * Method:    scasum
 * Signature: (ILjava/nio/FloatBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_scasum
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    scnrm2
 * Signature: (ILjava/nio/FloatBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_scnrm2
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    scopy
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_scopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sdot
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_sdot
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sgbmv
 * Signature: (CIIIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sgbmv
  (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sgemm
 * Signature: (CCIIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sgemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sgemv
 * Signature: (CIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sgemv
  (JNIEnv *, jclass, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sger
 * Signature: (IIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sger
  (JNIEnv *, jclass, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    snrm2
 * Signature: (ILjava/nio/FloatBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_com_fhg_la_Blas_snrm2
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    srot
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFF)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_srot
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint, jfloat, jfloat);

/*
 * Class:     com_fhg_la_Blas
 * Method:    srotg
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_srotg
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssbmv
 * Signature: (CIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssbmv
  (JNIEnv *, jclass, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sscal
 * Signature: (IFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sscal
  (JNIEnv *, jclass, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sspmv
 * Signature: (CIFLjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sspmv
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sspr2
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sspr2
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sspr
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sspr
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    sswap
 * Signature: (ILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_sswap
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssymm
 * Signature: (CCIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssymm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssymv
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssymv
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssyr2
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssyr2
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssyr2k
 * Signature: (CCIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssyr2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssyr
 * Signature: (CIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssyr
  (JNIEnv *, jclass, jchar, jint, jfloat, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ssyrk
 * Signature: (CCIIFLjava/nio/FloatBuffer;IIFLjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ssyrk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jfloat, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    stbmv
 * Signature: (CCCIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_stbmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    stbsv
 * Signature: (CCCIILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_stbsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    stpmv
 * Signature: (CCCILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_stpmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    stpsv
 * Signature: (CCCILjava/nio/FloatBuffer;ILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_stpsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    strmm
 * Signature: (CCCCIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_strmm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    strmv
 * Signature: (CCCILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_strmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    strsm
 * Signature: (CCCCIIFLjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_strsm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jfloat, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    strsv
 * Signature: (CCCILjava/nio/FloatBuffer;IILjava/nio/FloatBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_strsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zaxpy
 * Signature: (ILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zaxpy
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zcopy
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zcopy
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zdotc
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)Lcom/fhg/core/DoubleComplex;
 */
JNIEXPORT jobject JNICALL Java_com_fhg_la_Blas_zdotc
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zdotu
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)Lcom/fhg/core/DoubleComplex;
 */
JNIEXPORT jobject JNICALL Java_com_fhg_la_Blas_zdotu
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zdscal
 * Signature: (IDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zdscal
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zgbmv
 * Signature: (CIIIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zgbmv
  (JNIEnv *, jclass, jchar, jint, jint, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zgemm
 * Signature: (CCIIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zgemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zgemv
 * Signature: (CIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zgemv
  (JNIEnv *, jclass, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zgerc
 * Signature: (IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zgerc
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zgeru
 * Signature: (IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zgeru
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhbmv
 * Signature: (CIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhbmv
  (JNIEnv *, jclass, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhemm
 * Signature: (CCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhemv
 * Signature: (CILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhemv
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zher2
 * Signature: (CILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zher2
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zher2k
 * Signature: (CCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zher2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zher
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zher
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zherk
 * Signature: (CCIIDLjava/nio/DoubleBuffer;IIDLjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zherk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jdouble, jobject, jint, jint, jdouble, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhpmv
 * Signature: (CILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhpmv
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhpr2
 * Signature: (CILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhpr2
  (JNIEnv *, jclass, jchar, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zhpr
 * Signature: (CIDLjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zhpr
  (JNIEnv *, jclass, jchar, jint, jdouble, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zrotg
 * Signature: (Lcom/fhg/core/DoubleComplex;Lcom/fhg/core/DoubleComplex;DLcom/fhg/core/DoubleComplex;)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zrotg
  (JNIEnv *, jclass, jobject, jobject, jdouble, jobject);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zscal
 * Signature: (ILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zscal
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zswap
 * Signature: (ILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zswap
  (JNIEnv *, jclass, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zsymm
 * Signature: (CCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zsymm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zsyr2k
 * Signature: (CCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zsyr2k
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    zsyrk
 * Signature: (CCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_zsyrk
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztbmv
 * Signature: (CCCIILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztbmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztbsv
 * Signature: (CCCIILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztbsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztpmv
 * Signature: (CCCILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztpmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztpsv
 * Signature: (CCCILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztpsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztrmm
 * Signature: (CCCCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztrmm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztrmv
 * Signature: (CCCILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztrmv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztrsm
 * Signature: (CCCCIILcom/fhg/core/DoubleComplex;Ljava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztrsm
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jint, jint, jobject, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     com_fhg_la_Blas
 * Method:    ztrsv
 * Signature: (CCCILjava/nio/DoubleBuffer;IILjava/nio/DoubleBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_Blas_ztrsv
  (JNIEnv *, jclass, jchar, jchar, jchar, jint, jobject, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
