/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhg_la_MyNativeClass */

#ifndef _Included_com_fhg_la_MyNativeClass
#define _Included_com_fhg_la_MyNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhg_la_MyNativeClass
 * Method:    dot
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_fhg_la_MyNativeClass_dot
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
