/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhg_la_BlasLevel1 */

#ifndef _Included_com_fhg_la_BlasLevel1
#define _Included_com_fhg_la_BlasLevel1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    drotg
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_drotg
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    drot
 * Signature: (ILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;IDD)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_drot
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint, jdouble, jdouble);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    dswap
 * Signature: (ILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_dswap
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    dscal
 * Signature: (IDLjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_dscal
  (JNIEnv *, jclass, jint, jdouble, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    dcopy
 * Signature: (ILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_dcopy
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    daxpy
 * Signature: (IDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel1_daxpy
  (JNIEnv *, jclass, jint, jdouble, jobject, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    ddot
 * Signature: (ILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_BlasLevel1_ddot
  (JNIEnv *, jclass, jint, jobject, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    dnrm2
 * Signature: (ILjava/nio/DoubleBuffer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_BlasLevel1_dnrm2
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    dasum
 * Signature: (ILjava/nio/DoubleBuffer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_BlasLevel1_dasum
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel1
 * Method:    idamax
 * Signature: (ILjava/nio/DoubleBuffer;I)D
 */
JNIEXPORT jdouble JNICALL Java_com_fhg_la_BlasLevel1_idamax
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
