/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhg_la_BlasLevel2 */

#ifndef _Included_com_fhg_la_BlasLevel2
#define _Included_com_fhg_la_BlasLevel2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhg_la_BlasLevel2
 * Method:    dgemv
 * Signature: (CIIDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;IDLjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel2_dgemv
  (JNIEnv *, jclass, jchar, jint, jint, jdouble, jobject, jint, jobject, jint, jdouble, jobject, jint);

/*
 * Class:     com_fhg_la_BlasLevel2
 * Method:    dger
 * Signature: (IIDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel2_dger
  (JNIEnv *, jclass, jint, jint, jdouble, jobject, jint, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
