/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fhg_la_BlasLevel3 */

#ifndef _Included_com_fhg_la_BlasLevel3
#define _Included_com_fhg_la_BlasLevel3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fhg_la_BlasLevel3
 * Method:    dgemm
 * Signature: (CCIIIDLjava/nio/DoubleBuffer;ILjava/nio/DoubleBuffer;IDLjava/nio/DoubleBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_fhg_la_BlasLevel3_dgemm
  (JNIEnv *, jclass, jchar, jchar, jint, jint, jint, jdouble, jobject, jint, jobject, jint, jdouble, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
